### ISSUE TITLE
Does not work on Foundry VTT v9 - Lancer 1.2.0

### ISSUE THREAD

**Issue by harmonixerdream** [BoltsJ/li-player-request#2]
Tested with no modules outside of the required and was player is unable to start a prompt like previous versions. 

https://puu.sh/J4Rui.png 

Unsure if this is user error, but rolling back the server to previous versions functions as normal. Tested with 4 different players on 2 different worlds

**Comment by BoltsJ** [comment]
Were there any error popups or errors in the dev console?

**Comment by harmonixerdream** [comment]
Just tested with different players, only 2 this time. I apologize. Nothing displayed in console on either mine or the players end.

**Comment by BoltsJ** [comment]
Cool. Thanks for checking. I'll look into this more on Wednesday. I'm guessing it's probably not initializing correctly due to V8 or v9 changes.

**Comment by harmonixerdream** [comment]
Can confirm, working as intended now. Thanks again!
